esphome:
  name: leak-detector-1

esp8266:
  # Adafruit Feather HUZZAH with ESP8266
  # https://www.adafruit.com/product/2821
  board: huzzah

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  #TODO: Change this password!
  password: "0123456789abcdef0123456789abcdef"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Leak-Detector-1 Fallback Hotspot"
    #TODO: Change this password!
    password: "AaBbCcDdEeFf"

captive_portal:

switch:
  - platform: gpio
    name: "Leak LED 1"
    id: leak_led_1
    pin:
      number: GPIO2
      inverted: true

# Bridging GPIO16 (with pulldown) and 3V will activate the sensor
# Bridging GPIO4  (with pullup)  and GND will activate the sensor (inverted)
binary_sensor:
  - platform: gpio
    device_class: moisture
    name: "Leak Sensor 1A"
    pin:
      number: GPIO4
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
      - delayed_on: 1000ms    #  1 second
      - delayed_off: 10000ms  # 10 seconds
    on_press:
      then:
        - switch.turn_on: leak_led_1
    on_release:
      then:
        - switch.turn_off: leak_led_1
  - platform: gpio
    device_class: moisture
    name: "Leak Sensor 1B"
    pin:
      number: GPIO12
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
      - delayed_on: 1000ms    #  1 second
      - delayed_off: 10000ms  # 10 seconds
    on_press:
      then:
        - switch.turn_on: leak_led_1
    on_release:
      then:
        - switch.turn_off: leak_led_1
